### ISSUE TITLE
Java error since v0.5.x

### ISSUE THREAD

**Issue by jonathanwiesel** [ChuckJonas/vscode-apex-pmd#79]
**Describe the bug**
I have configured to run the PMD when a class is saved, after saving I get an error

Seems to happen since the new v0.5.x

**Apex PMD Output**
```
Analyzing /Users/jonathanwiesel/.../xxx.cls
PMD Command: java -cp "/Users/jonathanwiesel/.vscode/extensions/chuckjonas.apex-pmd-0.5.1/bin/pmd/lib/*:/Users/jonathanwiesel/.../*:/usr/local/Cellar/pmd/6.23.0/libexec/lib/*" net.sourceforge.pmd.PMD -f csv -no-cache -d "/Users/jonathanwiesel/.../xxx.cls" -R "/Users/jonathanwiesel/.apex_ruleset.xml"
stderr:Exception in thread "main" 
stderr:java.util.ServiceConfigurationError: net.sourceforge.pmd.lang.Language: Provider net.sourceforge.pmd.lang.java.JavaLanguageModule could not be instantiated

stderr:	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)

stderr:	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at net.sourceforge.pmd.lang.LanguageRegistry.<init>(LanguageRegistry.java:35)
	at net.sourceforge.pmd.lang.LanguageRegistry.<clinit>(LanguageRegistry.java:24)
	at net.sourceforge.pmd.cli.PMDParameters.getLanguage(PMDParameters.java:295)
	at net.sourceforge.pmd.cli.PMDParameters.toConfiguration(PMDParameters.java:208)
	at net.sourceforge.pmd.PMD.run(PMD.java:471)
	at net.sourceforge.pmd.cli.PMDCommandLineInterface.run(PMDCommandLineInterface.java:166)
stderr:
	at net.sourceforge.pmd.PMD.main(PMD.java:451)
Caused by: java.lang.NoSuchMethodError: 'void net.sourceforge.pmd.lang.java.JavaLanguageModule.addVersions(net.sourceforge.pmd.lang.LanguageVersionHandler, boolean, java.lang.String[])'
stderr:
	at net.sourceforge.pmd.lang.java.JavaLanguageModule.<init>(JavaLanguageModule.java:22)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

stderr:	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 9 more

Failed Exit Code: 1
```

**Apex PMD Settings**
```
{
    "apexPMD.rulesets": [
        "/Users/jonathanwiesel/.apex_ruleset.xml"
    ],
    "apexPMD.additionalClassPaths": [
        "/usr/local/Cellar/pmd/6.23.0/libexec/lib/*"
    ],
    "apexPMD.showStdOut": true
}
```

- pmdPath: `/usr/local/bin/pmd`
- rulesetPath: `/Users/jonathanwiesel/.apex_ruleset.xml`

**Versions (please complete the following information):**
 - OS: macOS 10.14.4
 - vscode: v1.47.2

**Comment by jonathanwiesel** [comment]
Never mind, updating the PMD binary to 6.26 made it work again.
